language: python
python:
  - "2.7"
install:
    # All these conda hoops are just there to install pandas, which is
    # very little used. If panda usage does not increase I guess it
    # should be removed.

    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export CONDA_HOME="$HOME/miniconda"
    - export PATH="$CONDA_HOME/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda install pandas numpy

    - pip install -r requirements-travis.txt

env:
  global:
    - DJANGO_SETTINGS_MODULE=friskby.settings
    - DATABASE_URL=sqlite:////$TRAVIS_BUILD_DIR/db.sqlite
    - FRISKBY_DEBUG=True
    - TZ=Europe/Oslo


script:
  - python manage.py test
