# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0027_auto_20160109_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datainfo',
            name='location',
        ),
        migrations.RemoveField(
            model_name='datainfo',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='datainfo',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='datavalue',
            name='data_info',
        ),
        migrations.RemoveField(
            model_name='datavalue',
            name='data_type',
        ),
        migrations.DeleteModel(
            name='DataInfo',
        ),
        migrations.DeleteModel(
            name='DataValue',
        ),
    ]
