# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0028_auto_20160502_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='location',
        ),
    ]
