# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0030_remove_rawdata_parsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
