# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_key', '0001_initial'),
        ('sensor', '0033_auto_20160525_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='post_key',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='api_key.ApiKey'),
            preserve_default=False,
        ),
    ]
