# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0034_device_post_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='post_key',
        ),
    ]
