# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0035_remove_sensor_post_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='client_version',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
