# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('git_version', '0001_initial'),
        ('sensor', '0036_device_client_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='git_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='git_version.GitVersion'),
        ),
    ]
