# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0037_device_git_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='locked',
            field=models.BooleanField(default=True),
        ),
    ]
