# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0045_auto_20170217_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='id',
            new_name='sensor_id',
        ),
    ]
