# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0046_auto_20170217_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawdata',
            name='string_value',
        ),
    ]
