# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 14:19
from __future__ import unicode_literals

from django.db import migrations, models




def forwards(apps, schema_editor):
    if not schema_editor.connection.alias == 'default':
        return
    sensor = apps.get_model('sensor', 'Sensor')
    s_id = 0
    for row in sensor.objects.all().order_by('sensor_id'):
        s_id += 1
        row.s_id = s_id
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0051_remove_rawdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='s_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RunPython(forwards)
    ]
