# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 17:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0052_sensor_s_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='s_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_id',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(regex=b'^[-_:a-zA-Z0-9]+$')], verbose_name=b'Sensor ID'),
        )
    ]
