# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0055_auto_20170307_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementtype',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name=b'Type of measurement'),
        ),
    ]
