# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0056_auto_20170314_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='s_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sensor.Sensor'),
            preserve_default=False,
        ),
    ]
