# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-02 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0057_auto_20170319_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawdata',
            old_name='sensor_id',
            new_name='sensor_string_id',
        ),
    ]
