# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-02 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0059_auto_20170402_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawdata',
            name='sensor_string_id',
        ),
    ]
