# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-08 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0060_remove_rawdata_sensor_string_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='channel',
            field=models.CharField(choices=[(b'stable', b'Stable'), (b'latest', b'Latest (development channel)')], default=b'stable', max_length=128),
        ),
    ]
