# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythoncall', '0001_initial'),
        ('filter', '0003_auto_20151227_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='code',
        ),
        migrations.RemoveField(
            model_name='transform',
            name='code',
        ),
        migrations.AddField(
            model_name='filter',
            name='python_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pythoncall.PythonCall'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transform',
            name='python_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pythoncall.PythonCall'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PythonCode',
        ),
    ]
