# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pythoncall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('html_code', models.TextField()),
                ('python_callable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythoncall.PythonCall')),
            ],
        ),
    ]
