# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 20:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 19, 20, 8, 8, 319522, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
