# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0002_plot_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='html_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='last_update',
            field=models.DateTimeField(blank=True),
        ),
    ]
