# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0003_auto_20160524_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='tag',
            field=models.CharField(default='ALL', max_length=128),
            preserve_default=False,
        ),
    ]
