# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0037_device_git_version'),
        ('plot', '0004_plot_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePlot',
            fields=[
                ('plot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plot.Plot')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.Device')),
            ],
            bases=('plot.plot',),
        ),
    ]
