# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0005_deviceplot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='python_callable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pythoncall.PythonCall'),
        ),
    ]
