# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=128, verbose_name='Git ref')),
                ('repo', models.CharField(default='https://github.com/FriskbyBergen/friskby', max_length=128, verbose_name='Git repo')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
            ],
        ),
    ]
