# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_version', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitversion',
            name='repo',
            field=models.CharField(default='https://github.com/FriskbyBergen/RPiParticle', max_length=128, verbose_name='Git repo'),
        ),
    ]
