# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_version', '0002_auto_20160619_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitversion',
            name='follow_head',
            field=models.BooleanField(default=False),
        ),
    ]
